# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1        # お好みのバージョンを指定
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff
    rev: v0.0.281      # お好みのバージョンを指定
    hooks:
      - id: ruff
        args: [--fix]   # 自動修正を有効化

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0        # お好みのバージョンを指定
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
 